spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.177.11:3306/test?characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
name: spring boot
age: 18
content: "name: ${name}, age: ${age}" 
user:
  name: newuser
  age: 20


  
  
#日志
#logging.file=D:/logs/springboot.log
#logging.level.org.springframework.web=debug

#配置servlet容器
#端口，默认8080
#server.port=80
#用户会话session过期时间，以秒为单位
#server.session.timeout=30
#配置访问路径，默认为/
#server.context-path=

#配置tomcat
#配置tomcat编码，默认为UTF-8
#server.tomcat.uri-encoding=
#tomcat是否开启压缩，默认为关闭off
#server.tomcat.compression=